//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_WindowsFormsApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_std
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string city { get; set; }
    }
}
